/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness and configuration summary.
         *
         *     Token-guarded when a token is configured: on a hosted deployment the engine is
         *     reachable at `/engine/*`, so an unauthenticated endpoint would leak provider
         *     and session-count detail to anyone who guesses the path.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Answers a question with citations and the groundedness gate applied.
         */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Streams the answer as SSE: citations, status, tokens, then done.
         */
        post: operations["chat_stream_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate
         * @description Runs the Ragas-style metric suite.
         */
        post: operations["evaluate_v1_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert Pipeline
         * @description Builds (or replaces) the session index from the uploaded PDFs.
         */
        post: operations["upsert_pipeline_v1_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Reset Session
         * @description Purges the index, documents and history for a session.
         */
        delete: operations["reset_session_v1_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{session_id}/citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Citations
         * @description Returns the citation catalogue for an indexed session.
         */
        get: operations["session_citations_v1_session__session_id__citations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Validates the provider, key, model and embedding width.
         */
        post: operations["test_connection_v1_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description `POST /v1/chat` body.
         */
        ChatRequest: {
            /** Question */
            question: string;
            session: components["schemas"]["EngineSession"];
        };
        /**
         * ChatResponse
         * @description `POST /v1/chat` result.
         */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["CitationModel"][];
            /** Faithfulness */
            faithfulness?: number | null;
            /** Fallback */
            fallback: boolean;
            /** Retrieved */
            retrieved: number;
            /** Standalonequery */
            standaloneQuery: string;
            usage: components["schemas"]["Usage"];
        };
        /**
         * ChatTurn
         * @description A retained conversation turn, used for query compression.
         */
        ChatTurn: {
            /** Citations */
            citations?: components["schemas"]["CitationModel"][];
            /** Content */
            content: string;
            /**
             * Createdat
             * @default
             */
            createdAt: string;
            /**
             * Fallback
             * @default false
             */
            fallback: boolean;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /**
         * CitationModel
         * @description A retrieved source surfaced before the first token.
         */
        CitationModel: {
            /** Chunkid */
            chunkId: string;
            /** Documentid */
            documentId: string;
            /** Documentname */
            documentName: string;
            /** Page */
            page: number;
            /** Score */
            score: number;
            /** Snippet */
            snippet: string;
        };
        /**
         * DocumentSummary
         * @description Indexed document summary returned to the browser.
         */
        DocumentSummary: {
            /** Chunkcount */
            chunkCount: number;
            /** Hasimages */
            hasImages: boolean;
            /** Id */
            id: string;
            /** Imagecount */
            imageCount: number;
            /** Name */
            name: string;
            /** Pagecount */
            pageCount: number;
            /** Sizebytes */
            sizeBytes: number;
        };
        /**
         * EngineDocument
         * @description A PDF handed to the engine for indexing.
         */
        EngineDocument: {
            /** Base64 */
            base64: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Pagecount */
            pageCount: number;
            /** Sizebytes */
            sizeBytes: number;
        };
        /**
         * EngineSession
         * @description Everything the engine needs to answer or evaluate for one session.
         */
        EngineSession: {
            /**
             * Apikey
             * @default
             */
            apiKey: string;
            config: components["schemas"]["PipelineConfig"];
            /** Documents */
            documents?: components["schemas"]["EngineDocument"][];
            /** History */
            history?: components["schemas"]["ChatTurn"][];
            /** Sessionid */
            sessionId: string;
        };
        /**
         * EvaluateRequest
         * @description `POST /v1/evaluate` body.
         */
        EvaluateRequest: {
            /**
             * Samplecount
             * @default 4
             */
            sampleCount: number;
            session: components["schemas"]["EngineSession"];
        };
        /**
         * EvaluationReport
         * @description `POST /v1/evaluate` result.
         */
        EvaluationReport: {
            /**
             * Category
             * @default Retrieval Augmented Generation
             * @constant
             */
            category: "Retrieval Augmented Generation";
            /** Createdat */
            createdAt: string;
            /** Documentcount */
            documentCount: number;
            /** Durationms */
            durationMs: number;
            /** Metrics */
            metrics: components["schemas"]["MetricResult"][];
            /** Samplecount */
            sampleCount: number;
            /** Samples */
            samples: components["schemas"]["EvaluationSample"][];
        };
        /**
         * EvaluationSample
         * @description A single evaluated question, retained for inspection.
         */
        EvaluationSample: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["CitationModel"][];
            /** Contexts */
            contexts: string[];
            /** Fallback */
            fallback: boolean;
            /** Groundtruth */
            groundTruth?: string | null;
            /** Question */
            question: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description `GET /health` result.
         */
        HealthResponse: {
            /** Embedding Models */
            embedding_models: string[];
            /** Hosted */
            hosted: boolean;
            /** Providers */
            providers: string[];
            /** Sessions */
            sessions: number;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * MetricResult
         * @description One Ragas-style metric score.
         */
        MetricResult: {
            /** Metric */
            metric: string;
            /** Reason */
            reason: string;
            /** Samples */
            samples: number;
            /** Score */
            score: number | "N/A";
            /** Skippedreason */
            skippedReason?: string | null;
        };
        /**
         * PipelineConfig
         * @description Immutable pipeline configuration, validated on arrival.
         */
        PipelineConfig: {
            /** Baseurl */
            baseUrl: string;
            /** Chunkoverlappercent */
            chunkOverlapPercent: number;
            /** Chunkoverlaptokens */
            chunkOverlapTokens: number;
            /** Chunksize */
            chunkSize: number;
            /**
             * Distancemetric
             * @enum {string}
             */
            distanceMetric: "cosine" | "dot" | "euclidean";
            /** Embeddingdimension */
            embeddingDimension: number;
            /**
             * Embeddingmodel
             * @enum {string}
             */
            embeddingModel: "text-embedding-3-small" | "text-embedding-3-large" | "nomic-embed-text" | "bge-m3" | "embeddinggemma" | "mxbai-embed-large";
            /** Maxinputtokens */
            maxInputTokens: number;
            /** Model */
            model: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "vocareum" | "deepseek" | "ollama";
            /**
             * Retrievalmode
             * @enum {string}
             */
            retrievalMode: "context-injection" | "agentic";
            /** Topk */
            topK: number;
        };
        /**
         * ResetResponse
         * @description `DELETE /v1/session/{id}` result.
         */
        ResetResponse: {
            /** Cleared */
            cleared: boolean;
        };
        /**
         * TestConnectionRequest
         * @description `POST /v1/test` body.
         */
        TestConnectionRequest: {
            session: components["schemas"]["EngineSession"];
        };
        /**
         * TestConnectionResponse
         * @description `POST /v1/test` result.
         */
        TestConnectionResponse: {
            /** Embeddingdimension */
            embeddingDimension: number;
            /** Embeddingprobe */
            embeddingProbe: boolean;
            /** Latencyms */
            latencyMs: number;
            /** Modelecho */
            modelEcho: string;
            /** Reachable */
            reachable: boolean;
        };
        /**
         * UpsertResponse
         * @description `POST /v1/pipeline` result.
         */
        UpsertResponse: {
            /** Chunkcount */
            chunkCount: number;
            /** Citations */
            citations: components["schemas"]["CitationModel"][];
            /** Documents */
            documents: components["schemas"]["DocumentSummary"][];
            /** Enginesessionid */
            engineSessionId: string;
            /** Multimodal */
            multimodal: boolean;
        };
        /**
         * Usage
         * @description Token accounting for cost attribution.
         */
        Usage: {
            /**
             * Completiontokens
             * @default 0
             */
            completionTokens: number;
            /**
             * Prompttokens
             * @default 0
             */
            promptTokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_v1_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_pipeline_v1_pipeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpsertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_session_v1_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_citations_v1_session__session_id__citations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_v1_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
